/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Rueda;
import Modelo.CasillaNegra;
import Modelo.CasillaRoja;
import Modelo.CasillaVerde;

/**
 *
 * @author PC
 */
public class Ruleta extends javax.swing.JFrame {

    /**
     * Creates new form Ruleta
     * 
     */
    CasillaNegra cane;
    CasillaRoja caro;
    CasillaVerde cave;
    Rueda ruedaGirando;    
    public Ruleta() {
        initComponents();
        ruedaGirando=new Rueda();
        cane= new CasillaNegra();
        caro= new CasillaRoja();
        cave= new CasillaVerde();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Empezar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ruletita = new javax.swing.JLabel();
        cero = new javax.swing.JLabel();
        uno = new javax.swing.JLabel();
        dos = new javax.swing.JLabel();
        tres = new javax.swing.JLabel();
        cuatro = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        seis = new javax.swing.JLabel();
        siete = new javax.swing.JLabel();
        ocho = new javax.swing.JLabel();
        nueve = new javax.swing.JLabel();
        diez = new javax.swing.JLabel();
        once = new javax.swing.JLabel();
        doce = new javax.swing.JLabel();
        cuatro_nums = new javax.swing.JLabel();
        trece = new javax.swing.JLabel();
        catorce = new javax.swing.JLabel();
        quince = new javax.swing.JLabel();
        dieciseis = new javax.swing.JLabel();
        diecisiete = new javax.swing.JLabel();
        dieciocho = new javax.swing.JLabel();
        diecinueve = new javax.swing.JLabel();
        veinte = new javax.swing.JLabel();
        veintiuno = new javax.swing.JLabel();
        ventidos = new javax.swing.JLabel();
        ventitres = new javax.swing.JLabel();
        venticuatro = new javax.swing.JLabel();
        venticinco = new javax.swing.JLabel();
        ventiseis = new javax.swing.JLabel();
        ventisiete = new javax.swing.JLabel();
        ventiocho = new javax.swing.JLabel();
        ventinueve = new javax.swing.JLabel();
        treinta = new javax.swing.JLabel();
        trentauno = new javax.swing.JLabel();
        trentados = new javax.swing.JLabel();
        trentatres = new javax.swing.JLabel();
        trentacuatro = new javax.swing.JLabel();
        trentacinco = new javax.swing.JLabel();
        trentaseis = new javax.swing.JLabel();
        rojito = new javax.swing.JLabel();
        negrito = new javax.swing.JLabel();
        pri_docena = new javax.swing.JLabel();
        dos_docena = new javax.swing.JLabel();
        tres_docena = new javax.swing.JLabel();
        prim_dieciocho = new javax.swing.JLabel();
        pair = new javax.swing.JLabel();
        impair = new javax.swing.JLabel();
        seg_dieciocho = new javax.swing.JLabel();
        prim_fila = new javax.swing.JLabel();
        seg_fila = new javax.swing.JLabel();
        ter_fila = new javax.swing.JLabel();
        fichita = new javax.swing.JLabel();
        cero_tres = new javax.swing.JLabel();
        cero_dos = new javax.swing.JLabel();
        cero_uno = new javax.swing.JLabel();
        tres_seis = new javax.swing.JLabel();
        dos_cinco = new javax.swing.JLabel();
        uno_cuatro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Mesita = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASINO UMSS");
        setBackground(new java.awt.Color(0, 102, 51));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 5));
        jPanel1.setForeground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Empezar.setText("Empezar");
        Empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpezarActionPerformed(evt);
            }
        });
        jPanel1.add(Empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, -1));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        ruletita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ruletita3.png"))); // NOI18N
        jPanel1.add(ruletita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 310, 300));
        jPanel1.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 30, 30));
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 20, 30));

        dos.setText("jLabel4");
        jPanel1.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 20, 20));
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 20, 20));
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 20, 30));
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 20, 30));
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 20, 30));
        jPanel1.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 20, 30));
        jPanel1.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 20, 30));
        jPanel1.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 20, 30));
        jPanel1.add(diez, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 20, 30));
        jPanel1.add(once, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 20, 30));
        jPanel1.add(doce, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 20, 40));
        jPanel1.add(cuatro_nums, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 30, 10));
        jPanel1.add(trece, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 10, 30));
        jPanel1.add(catorce, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 10, 30));
        jPanel1.add(quince, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 10, 20));
        jPanel1.add(dieciseis, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 20, 20));
        jPanel1.add(diecisiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 20, 30));
        jPanel1.add(dieciocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 20, 20));
        jPanel1.add(diecinueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 10, 30));
        jPanel1.add(veinte, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 10, 30));
        jPanel1.add(veintiuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 10, 30));
        jPanel1.add(ventidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 20, 30));
        jPanel1.add(ventitres, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 20, 30));
        jPanel1.add(venticuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 20, 30));
        jPanel1.add(venticinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 10, 30));
        jPanel1.add(ventiseis, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 10, 30));
        jPanel1.add(ventisiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 10, 30));
        jPanel1.add(ventiocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 20, 30));
        jPanel1.add(ventinueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 20, 30));
        jPanel1.add(treinta, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 20, 20));
        jPanel1.add(trentauno, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 426, 20, 20));
        jPanel1.add(trentados, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 20, 30));
        jPanel1.add(trentatres, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 20, 20));
        jPanel1.add(trentacuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 20, 30));
        jPanel1.add(trentacinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 20, 30));
        jPanel1.add(trentaseis, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 20, 20));
        jPanel1.add(rojito, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 50, 20));
        jPanel1.add(negrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 50, 20));
        jPanel1.add(pri_docena, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 120, 20));
        jPanel1.add(dos_docena, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 130, 20));
        jPanel1.add(tres_docena, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 130, 20));
        jPanel1.add(prim_dieciocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 70, 30));
        jPanel1.add(pair, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 60, 30));
        jPanel1.add(impair, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 506, 60, 20));
        jPanel1.add(seg_dieciocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 500, 60, 30));
        jPanel1.add(prim_fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 416, 20, 40));
        jPanel1.add(seg_fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 20, 40));
        jPanel1.add(ter_fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 20, 40));

        fichita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fichitas.png"))); // NOI18N
        jPanel1.add(fichita, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 590, 290));
        jPanel1.add(cero_tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 326, 20, 20));
        jPanel1.add(cero_dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 376, 20, 20));
        jPanel1.add(cero_uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 20, 30));
        jPanel1.add(tres_seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 10, 20));
        jPanel1.add(dos_cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 10, 20));
        jPanel1.add(uno_cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 10, 20));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 320, 10, 30));

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        Mesita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mesa2.jpeg"))); // NOI18N
        jPanel1.add(Mesita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 520, 260));

        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jLabel18.setText("jLabel18");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        jLabel24.setText("jLabel24");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        jLabel25.setText("jLabel25");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        jLabel21.setText("jLabel21");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        jLabel22.setText("jLabel22");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        jLabel26.setText("jLabel26");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, -1, -1));

        jLabel27.setText("jLabel27");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jLabel28.setText("jLabel28");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, -1));

        jLabel29.setText("jLabel29");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));

        jLabel30.setText("jLabel30");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        jLabel31.setText("jLabel31");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        jLabel32.setText("jLabel32");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        jLabel33.setText("jLabel33");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        jLabel34.setText("jLabel34");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, -1, -1));

        jLabel35.setText("jLabel35");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, -1));

        jLabel36.setText("jLabel36");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));

        jLabel37.setText("jLabel37");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        jLabel38.setText("jLabel38");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpezarActionPerformed
        int numero=ruedaGirando.aleatorio();
        if(cane.isCasillero(numero)){
            jLabel2.setText(cane.getColor());
        }else if(caro.isCasillero(numero)){
            jLabel2.setText(caro.getColor());
        }else if (cave.isCasillero(numero)){
            jLabel2.setText(cave.getColor());
        }
        //String Color=
        jLabel1.setText(numero+"");
    }//GEN-LAST:event_EmpezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Empezar;
    private javax.swing.JLabel Mesita;
    private javax.swing.JLabel catorce;
    private javax.swing.JLabel cero;
    private javax.swing.JLabel cero_dos;
    private javax.swing.JLabel cero_tres;
    private javax.swing.JLabel cero_uno;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel cuatro;
    private javax.swing.JLabel cuatro_nums;
    private javax.swing.JLabel diecinueve;
    private javax.swing.JLabel dieciocho;
    private javax.swing.JLabel dieciseis;
    private javax.swing.JLabel diecisiete;
    private javax.swing.JLabel diez;
    private javax.swing.JLabel doce;
    private javax.swing.JLabel dos;
    private javax.swing.JLabel dos_cinco;
    private javax.swing.JLabel dos_docena;
    private javax.swing.JLabel fichita;
    private javax.swing.JLabel impair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel negrito;
    private javax.swing.JLabel nueve;
    private javax.swing.JLabel ocho;
    private javax.swing.JLabel once;
    private javax.swing.JLabel pair;
    private javax.swing.JLabel pri_docena;
    private javax.swing.JLabel prim_dieciocho;
    private javax.swing.JLabel prim_fila;
    private javax.swing.JLabel quince;
    private javax.swing.JLabel rojito;
    private javax.swing.JLabel ruletita;
    private javax.swing.JLabel seg_dieciocho;
    private javax.swing.JLabel seg_fila;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel siete;
    private javax.swing.JLabel ter_fila;
    private javax.swing.JLabel trece;
    private javax.swing.JLabel treinta;
    private javax.swing.JLabel trentacinco;
    private javax.swing.JLabel trentacuatro;
    private javax.swing.JLabel trentados;
    private javax.swing.JLabel trentaseis;
    private javax.swing.JLabel trentatres;
    private javax.swing.JLabel trentauno;
    private javax.swing.JLabel tres;
    private javax.swing.JLabel tres_docena;
    private javax.swing.JLabel tres_seis;
    private javax.swing.JLabel uno;
    private javax.swing.JLabel uno_cuatro;
    private javax.swing.JLabel veinte;
    private javax.swing.JLabel veintiuno;
    private javax.swing.JLabel venticinco;
    private javax.swing.JLabel venticuatro;
    private javax.swing.JLabel ventidos;
    private javax.swing.JLabel ventinueve;
    private javax.swing.JLabel ventiocho;
    private javax.swing.JLabel ventiseis;
    private javax.swing.JLabel ventisiete;
    private javax.swing.JLabel ventitres;
    // End of variables declaration//GEN-END:variables
}
